#It gets keys with help of DOTENV gem from ".env" file.
#Always keep it in gitignore and load directly in your app.

development:
  secret_key_base: <%= ENV["DEVELOPMENT_SECRET_KEY_BASE"] %>

test:
  secret_key_base: <%= ENV["TEST_SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["PRODUCTION_SECRET_KEY_BASE"] %>
