#It gets keys with help of DOTENV gem from ".env" file.
#Always keep it in gitignore and load directly in your app.

development:
  secret_key_base: e56d879e6c6691742b9cefab596e50b1b27a7624f4c238e0b7cfadaf5e0050c391c612d01bb46b347ca9bb1033907691dc95b8a893b5099fd7db89a413cabedd

test:
  secret_key_base: <%= ENV["TEST_SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["PRODUCTION_SECRET_KEY_BASE"] %>
